### ISSUE TITLE
run_p2pool.py: error: unrecognized arguments ( username + password )

### ISSUE THREAD

**Issue by buechling** [forrestv/p2pool#240]
Did something change in the newest Version? i can not pass RPC username and password! As i don't use config files, this option would be great..

	python run_p2pool.py -net bitcoin -a 1DyhJMdAbxyQ7NbsM6SsX3kLci8xmT98bi --datadir bitcoin --give-author 1 --irc-announce --p2pool-port 9337 --max-conns 80 --outgoing-conns 8 -w 9336 -f 3 --bitcoind-rpc-port 8338 --bitcoind-p2p-port 8337 abc abc
	usage: run_p2pool.py [-h] [--version]
						 [--net {bitcoin,fastcoin,litecoin,terracoin}] [--testnet]
						 [--debug] [-a ADDRESS] [--datadir DATADIR]
						 [--logfile LOGFILE] [--merged MERGED_URLS]
						 [--give-author DONATION_PERCENTAGE] [--iocp]
						 [--irc-announce] [--no-bugreport] [--p2pool-port PORT]
						 [-n ADDR[:PORT]] [--disable-upnp] [--max-conns CONNS]
						 [--outgoing-conns CONNS] [--external-ip ADDR[:PORT]]
						 [--disable-advertise] [-w PORT or ADDR:PORT]
						 [-f FEE_PERCENTAGE]
						 [--bitcoind-config-path BITCOIND_CONFIG_PATH]
						 [--bitcoind-address BITCOIND_ADDRESS]
						 [--bitcoind-rpc-port BITCOIND_RPC_PORT]
						 [--bitcoind-rpc-ssl]
						 [--bitcoind-p2p-port BITCOIND_P2P_PORT]
						 [BITCOIND_RPCUSERPASS [BITCOIND_RPCUSERPASS ...]]
	run_p2pool.py: error: unrecognized arguments: abc abc

i moved from windows to linux (ssh) .. do i have to use some kind of magic like
"abc abc"
'abc abc'
!?

	python run_p2pool.py --version
	13.4-57-gdfad3cd
	python -V
	Python 2.7.6
	uname -a
	Linux f634 3.13.0-43-generic #72-Ubuntu SMP Mon Dec 8 19:35:06 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

**Comment by forrestv** [comment]
The error message is confusing, but the problem is that your first argument (`-net`) needs to have two dashes. I'm going to blame the confusing error message on the library that P2Pool uses for argument parsing, `argparse`.

**Comment by buechling** [comment]
ah i see! great! thank you for the fast support :)
